language: scala

scala:
- 2.11.12
- 2.12.6

jdk: oraclejdk8

sudo: required

services:
- docker

before_install:
- git fetch --tags

stages:
- name: test
- name: codecov
- name: release
  if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
  - stage: test
    script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
  - stage: codecov
    script: bash <(curl -s https://codecov.io/bash)
  - stage: release
    script: sbt clean ci-release

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
