language: scala

jdk: oraclejdk8

sudo: required

services:
- docker

before_install:
- git fetch --tags

stages:
- name: test
- name: release
  if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
  - stage: test
    script: sbt scalafmtCheck scalafmtSbtCheck
  - script: sbt clean coverage +test coverageReport && scripts/codecov
  - stage: release
    name: "Publishing to Sonatype"
    script: sbt clean ci-release

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
