language: scala

scala:
- 2.11.12
- 2.12.6

jdk: oraclejdk8

sudo: required

services:
- docker

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
- bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
